### ISSUE TITLE
Overriding defaults on TFT Gizmo will cause issues

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_CircuitPython_Gizmo#4]
I haven't actually tested this, but I just noticed this while working on the eink gizmo that overriding the default parameters will cause the private variables to not be initialized at all instead of using overriding values. Removing the underscores on those should fix it.

**Comment by makermelissa** [comment]
Ok, verified. Passing `dc=board.TX` as a parameter should have no effect, but causes it to crash with:
```
Traceback (most recent call last):
  File "code.py", line 12, in <module>
  File "/lib/adafruit_gizmo/tft_gizmo.py", line 55, in __init__
AttributeError: 'TFT_Gizmo' object has no attribute '_dc'
```
